---
#
# Show cisco.ise.guest_location Template
#

- name: Get guest_location
  cisco.ise.guest_location_info:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
  register: info

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

#
# ðŸž ERROR - Unsupported method exception
#
# - name: Get guest_location by id
#   when: info is defined
#     and info.ise_response | length > 0
#   loop: "{{ info.ise_response }}"
#   cisco.ise.guest_location_info:
#     id: "{{ item.id }}"
#   register: info

# - name: Show `info`
#   ansible.builtin.debug:
#     var: info
#     verbosity: 1

- name: Clear `resources`
  ansible.builtin.set_fact:
    resources: []

- name: Set `resources` and remove `id` and `link` attributes
  when: info is defined
    and info.results | count > 0
  loop: "{{ info.results }}"
  ansible.builtin.set_fact:
    resources: '{{ resources | default([]) + [ item
      | dict2items
      | rejectattr("key", "equalto", "id")
      | rejectattr("key", "equalto", "link")
      | list | items2dict ] }}'

- name: To YAML
  when: resources is defined
    and resources | count > 0
  delegate_to: localhost
  changed_when: false
  ansible.builtin.shell: "echo '\n\n{{ resources | to_nice_yaml(indent=2) }}'> /dev/tty"

- name: To YAML File | {{ dir_ise_configs }}/{{ resource_name }}.yaml
  when: resources is defined
    and resources | count > 0
  delegate_to: localhost
  vars:
    resource_name: guest_location
    resources: "{{ resources }}"
  ansible.builtin.template:
    src: templates/resource_template.j2
    dest: "{{ dir_ise_configs }}/{{ resource_name }}.yaml"
    mode: "0644"
