---
#
# Based on the *_info modules @
#   https://ciscoise.github.io/ansible-ise/main/html/plugins/
#
# Excluded *_status modules since those are not about Configuration
#

cisco_ise_modules:


  # ISE 3.1.0.451
  # ðŸ›‘ non-standard key:value pairs in a resultValue object :
  #
  # info:
  #   changed: false
  #   failed: false
  #   ise_response:
  #     resultValue:
  #     - name: version
  #       value: 3.1.0.451
  #     - name: patch information
  #       value: '0'
  #   info: ''
  #
  # - cisco.ise.system_config_version

  #
  # ðŸ›‘ These modules are for monitoring or operations - not configuration!
  #    Skip them.
  #
  # - cisco.ise.deployment
  # - cisco.ise.node_replication_status
  # - cisco.ise.csr
  # - cisco.ise.csr_export
  # - cisco.ise.trusted_certificate_export
  # - cisco.ise.trusted_certificate

  #
  # ðŸž? The error was: [404] - The URI requested is invalid or the resource requested
  #     Test with ISE 3.1.0.451
  #
  # - cisco.ise.node_deployment
  # - cisco.ise.node_group
  # - cisco.ise.pan_ha
  # - cisco.ise.session_service_node
  # - cisco.ise.node



  #
  # ðŸ›‘  Must enable pxGrid for it to work otherwise you get a
  #    [404] - The resource requested does not exist.
  # - cisco.ise.px_grid_node





  # ISE 3.1.0.451
  # ðŸ›‘ Requires hostName attribute!
  # ðŸ›‘ info.ise_response.respone contains all details; get-by-id not needed
  # ðŸ›‘ Must iterate for each node or only PAN node?
  #
  # ok: [ise.securitydemo.net] =>
  # info:
  #   changed: false
  #   failed: false
  #   ise_response:
  #     nextPage: null
  #     previousPage: null
  #     response:
  #     - expirationDate: Thu Feb 26 03:06:07 UTC 2026
  #       friendlyName: Default self-signed saml server certificate - CN=SAML_ise.securitydemo.net
  #       groupTag: ''
  #       id: 2abb75f3-bbfc-4722-8fa9-e3e03ff890f0
  #       issuedBy: SAML_ise.securitydemo.net
  #       issuedTo: SAML_ise.securitydemo.net
  #       keySize: 4096
  #       link:
  #         href: https://ise.securitydemo.net/api/v1/certs/system-certificate/ise/2abb75f3-bbfc-4722-8fa9-e3e03ff890f0
  #         rel: self
  #         type: application/json
  #       portalsUsingTheTag: ''
  #       selfSigned: true
  #       serialNumberDecimalFormat: '127905562653318915182575672544073847719'
  #       sha256Fingerprint: 6c23d78dc75e9bf3b4bdad6a970da28c6679d93cd090e9b69c63fba2ba3d5e2a
  #       signatureAlgorithm: SHA384WITHRSA
  #       usedBy: SAML
  #       validFrom: Sat Feb 27 03:06:07 UTC 2021
  #
  # - cisco.ise.system_certificate




  # ISE 3.1.0.451
  # ðŸ›‘ info.ise_response.respone contains all details; get-by-id not needed
  #
  # ok: [ise.securitydemo.net] =>
  # info:
  #   changed: false
  #   failed: false
  #   ise_response:
  #     response:
  #     - name: dCloud_FTP
  #       password: ''
  #       path: /
  #       protocol: FTP
  #       serverName: 198.18.133.1
  #       userName: ''
  #     version: 1.0.0
  #   info: ''
  #
  # - cisco.ise.repository


  - cisco.ise.admin_user




  #
  # Identity Stores & Exernal Servers
  #
  - cisco.ise.external_radius_server
  - cisco.ise.radius_server_sequence
  - cisco.ise.id_store_sequence
  - cisco.ise.active_directory
  # - cisco.ise.active_directory_groups_by_domain
  # - cisco.ise.active_directory_is_user_member_of_group
  # - cisco.ise.active_directory_trusted_domains
  # - cisco.ise.active_directory_user_groups
  - cisco.ise.rest_id_store



  #
  # âœ… Network Access Policy
  #
  - cisco.ise.allowed_protocols
  - cisco.ise.downloadable_acl


  # ðŸ›‘  Bug in Ansible code through v1.2.1:
  #    [404] - The URI requested is invalid or the resource requested
  # - cisco.ise.network_access_profiles


  #
  # convenience API for cisco.ise.authorization_profile
  # Only id & name attributes given:
  #   - id: 6ef23ff0-8bff-11e6-996c-525400b48521
  #     name: DenyAccess
  #
  - cisco.ise.authorization_profile



  # ðŸ›‘ info.ise_response.response contains all details; get-by-id not needed
  - cisco.ise.network_access_dictionary



  # ISE 3.1.0.451
  # ðŸ›‘ requires attribute: dictionaryName
  # ðŸ›‘ info.ise_response.response contains all details; get-by-id not needed
  - cisco.ise.network_access_dictionary_attribute



  # ðŸ›‘ info.ise_response.response contains all details; get-by-id not needed
  - cisco.ise.network_access_dictionary_attributes_authentication



  # ðŸ›‘ info.ise_response.response contains all details; get-by-id not needed
  - cisco.ise.network_access_dictionary_attributes_authorization



  # ðŸ›‘ info.ise_response.response contains all details; get-by-id not needed
  - cisco.ise.network_access_dictionary_attributes_policy_set




  # ISE 3.1.0.451
  # ðŸ›‘   msg: Unexpected failure during module execution.
  #
  - cisco.ise.network_access_authentication_rules
  - cisco.ise.network_access_authorization_rules
  - cisco.ise.network_access_local_exception_rules
  - cisco.ise.network_access_global_exception_rules
  - cisco.ise.network_access_conditions_for_authentication_rule
  - cisco.ise.network_access_conditions_for_authorization_rule
  - cisco.ise.network_access_conditions_for_policy_set
  - cisco.ise.network_access_conditions
  - cisco.ise.network_access_identity_stores
  - cisco.ise.network_access_network_condition
  - cisco.ise.network_access_policy_set
  - cisco.ise.network_access_security_groups
  - cisco.ise.network_access_service_name
  - cisco.ise.network_access_time_date_conditions



  #
  # Device Administration Policy
  #
  # - cisco.ise.device_administration_authentication_rules
  # - cisco.ise.device_administration_authorization_exception_rules
  # - cisco.ise.device_administration_authorization_global_exception_rules
  # - cisco.ise.device_administration_authorization_rules
  # - cisco.ise.device_administration_command_set
  # - cisco.ise.device_administration_conditions_for_authentication_rule
  # - cisco.ise.device_administration_conditions_for_authorization_rule
  # - cisco.ise.device_administration_conditions_for_policy_set
  # - cisco.ise.device_administration_conditions
  # - cisco.ise.device_administration_dictionary_attributes_authentication
  # - cisco.ise.device_administration_dictionary_attributes_authorization
  # - cisco.ise.device_administration_dictionary_attributes_policy_set
  # - cisco.ise.device_administration_identity_stores
  # - cisco.ise.device_administration_network_conditions
  # - cisco.ise.device_administration_policy_set
  # - cisco.ise.device_administration_profiles
  # - cisco.ise.device_administration_service_names
  # - cisco.ise.device_administration_time_date_conditions






  #
  # TACACS
  #
  - cisco.ise.tacacs_command_sets
  - cisco.ise.tacacs_external_servers
  - cisco.ise.tacacs_profile
  - cisco.ise.tacacs_server_sequence




  #
  # âœ… Endpoints
  #
  # - cisco.ise.endpoint_get_rejected_endpoints
  - cisco.ise.endpoint_group
  - cisco.ise.endpoint



  #
  # âœ… Users & Groups
  #
  - cisco.ise.identity_group
  - cisco.ise.internal_user



  #
  # âœ… Network Devices
  #
  - cisco.ise.network_device_group
  - cisco.ise.network_device




  #
  # Guest Users
  #



  # ISE 3.1.0.451
  # ðŸ›‘  405 GET guestlocation/{id}
  #     No POST guestlocation
  #     No PUT  guestlocation
  #
  - cisco.ise.guest_location




  #
  # âœ…
  #
  - cisco.ise.guest_type
  - cisco.ise.guest_ssid



  #
  # ðŸ›‘ Requires sponsor account!
  #
  - cisco.ise.guest_user



  #
  # Guest Portals
  #

  - cisco.ise.portal_global_setting
  - cisco.ise.portal
  - cisco.ise.portal_theme
  - cisco.ise.guest_smtp_notification_settings
  - cisco.ise.hotspot_portal
  - cisco.ise.self_registered_portal
  - cisco.ise.sponsor_group




  # ISE 3.1.0.451
  # ðŸ›‘  405 GET sponsorgroupmember/{id}
  #     No POST sponsorgroupmember
  #     No PUT  sponsorgroupmember
  #
  - cisco.ise.sponsor_group_member



  #
  # âœ…
  #
  - cisco.ise.sponsor_portal
  - cisco.ise.sponsored_guest_portal



  # ISE 3.1.0.451
  # ðŸ›‘  GET and POST /ers/config/smsprovider/{id} not supported!
  #
  # - cisco.ise.sms_provider



  #
  #  âœ… Profiling
  #
  - cisco.ise.profiler_profile



  #
  #  âœ… BYOD
  #
  - cisco.ise.byod_portal
  - cisco.ise.certificate_profile
  - cisco.ise.certificate_template
  - cisco.ise.my_device_portal
  - cisco.ise.native_supplicant_profile



  #
  #  âœ… TrustSec
  #
  - cisco.ise.sgt
  - cisco.ise.sg_acl
  - cisco.ise.egress_matrix_cell
  - cisco.ise.sg_mapping_group
  - cisco.ise.sg_mapping
  - cisco.ise.sg_to_vn_to_vlan

  - cisco.ise.sxp_connections
  - cisco.ise.sxp_local_bindings
  - cisco.ise.sxp_vpns




  #
  # Other
  #
  - cisco.ise.aci_bindings
  - cisco.ise.aci_settings
  - cisco.ise.anc_endpoint
  - cisco.ise.anc_policy
  - cisco.ise.filter_policy
  - cisco.ise.telemetry

...
